FROM python:3.4-slim

RUN apt-get update && apt-get -y install build-essential libdb-dev && mkdir /app

WORKDIR /app

COPY requirements.txt /app/

RUN pip install -r requirements.txt

COPY . /app

CMD scrapy
