FROM ruby:2.2-slim

LABEL vendor="Public Library of Science"

RUN apt-get update -qq && \
    apt-get install -y build-essential libsqlite3-dev libssl-dev && \
    gem install mailcatcher

# lower the attack surface, but does not lower the image size for some reason
RUN apt-get remove -y build-essential libssl-dev && apt-get autoremove -y

CMD ["mailcatcher", "--ip", "0.0.0.0", "--foreground"]
