FROM ruby:2.2-slim

RUN apt-get update -qq && apt-get install -y build-essential
RUN apt-get install -y libsqlite3-dev libssl-dev

RUN gem install mailcatcher

# lower the attack surface, but does not lower the image size for some reason
RUN apt-get remove -y build-essential libssl-dev
RUN apt-get autoremove -y

CMD ["mailcatcher", "--ip", "0.0.0.0", "--foreground"]
