defaults: &defaults
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: mediaTracker
  host: curationdb
  pool: 5
  username: tracker
  password: tracker
  # socket: /var/run/mysqld/mysqld.sock

# TODO: set these values to use a remote database?
