defaults: &defaults
  solr_url: http://api.plos.org/search
  cas_host: register.plos.org
  cas_port: 443
  cas_logout_url: https://register.plos.org/cas/logout

# TODO: turn these values into environment vars

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
