defaults: &defaults
  solr_url: http://api.plos.org/search
  cas_host: nedcas
  cas_port: 8443
  cas_logout_url: https://localhost:8443/cas/logout

# TODO: turn these values into environment vars

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
