version: '2'

services:

  wombat:
    extends:
      file: common.yml
      service: wombat
    image: plos/wombat:3.3.3
    volumes:
      # - $HOME/ambra_demo/themes:/root/themes
      - $DOCKERFILES/themes/minimal:/root/themes

  memcached:
    extends:
      file: common.yml
      service: memcached

  rhino:
    extends:
      file: common.yml
      service: rhino
    image: plos/rhino:2.2.2
    environment:
      - MODE=example
      - MYSQL_HOSTNAME=ambradb_demo
      - SOLR=http://solr_dummy:8080/select

  ambradb_demo:
    extends:
      file: common.yml
      service: ambradb
    ports:
      - "3307:3306"

  contentrepo:
    extends:
      file: common.yml
      service: contentrepo
    image: plos/contentrepo:1.2.0
    volumes:
      - /repodata
    environment:
      - STORE_TYPE=FileSystem
      - FS_DIRECTORY=/repodata
      # - FS_REPROXY_URL=urlhere

  repodb:
    extends:
      file: common.yml
      service: repodb

# HACK: to allow article rendering in wombat until plos-solr gets open sourced
  solr_dummy:
    image: solr:5-alpine
