version: '2'

# TODO: test ingestion and make sure content repo works in filesystem mode without mogile

services:

  # TODO: add wombat back once lockss issue is resolved: https://developer.plos.org/jira/browse/DPRO-3383?filter=-2
  # wombat:
  #   extends:
  #     file: common.yml
  #     service: wombat
  #   # image: plos/wombat:3.3.0
  #   volumes:
  #     - $HOME/data/plos-example-themes:/root/themes

  rhino:
    extends:
      file: common.yml
      service: rhino
    image: plos/rhino:2.2.0

  ambradb:
    extends:
      file: common.yml
      service: ambradb
    ports:
      - "3307:3306"

  contentrepo:
    extends:
      file: common.yml
      service: contentrepo
    image: plos/contentrepo:1.2.0
    volumes:
      - /repodata
    environment:
      - STORE_TYPE=FileSystem
      - FS_DIRECTORY=/repodata

  repodb:
    extends:
      file: common.yml
      service: repodb
