version: '2'

# TODO: test ingestion and make sure content repo works in filesystem mode without mogile

services:

  wombat:
    extends:
      file: common.yml
      service: wombat
    image: plos/wombat:3.3.2
    volumes:
      # - /tmp/plos-example-themes:/root/themes
      # - /tmp/themes:/root/themes
      - $HOME/ambra_demo/themes:/root/themes

  memcached:
    extends:
      file: common.yml
      service: memcached

  rhino:
    extends:
      file: common.yml
      service: rhino
    image: plos/rhino:2.2.2
    environment:
      - MODE=example
      - MYSQL_HOSTNAME=ambradb_demo

  ambradb_demo:
    extends:
      file: common.yml
      service: ambradb
    ports:
      - "3307:3306"

  contentrepo:
    extends:
      file: common.yml
      service: contentrepo
    image: plos/contentrepo:1.2.0
    volumes:
      - /repodata
    environment:
      - STORE_TYPE=FileSystem
      - FS_DIRECTORY=/repodata
      # - FS_REPROXY_URL=urlhere

  repodb:
    extends:
      file: common.yml
      service: repodb
