version: '2'

services:

  akita-lb:
    extends: traefik-lb
    command: --web --logLevel=DEBUG --docker --docker.constraints=tag==akita
    ports:
      - "81:80"

  akita:
    extends: akita-proxyable
    ports:
      - "81:80"

  akita-proxyable:
    image: plos/akita:develop
    environment:
      - NED_SERVICE=http://nedapi:8080/v1
      - MAILER_ADDRESS=mailcatcher
      - MAILER_PORT=1025
      - NED_USERAPP=dev
      - NED_PASSWORD=dev
      - CAS_URL=http://nedcas:8080
      - SECRET_KEY_BASE=superlongsecretgoeshere1234566789
      - EXACTTARGET_ID=
      - EXACTTARGET_SECRET=
      - SALESFORCE_HOST=
      - SALESFORCE_CLIENT_ID=
      - SALESFORCE_CLIENT_SECRET=
      - SALESFORCE_USERNAME=
      - SALESFORCE_PASSWORD=
      - SALESFORCE_CONSUMER_APP=
      - SALESFORCE_CONSUMER_PASSWORD=
      - MOODLE_TOKEN=
      - RECAPTCHA_SECRET=
      - KEYS_DIR=/akita_keys
      - JWT_SHARED_SECRET=db714af08c2a695ac04f7dd5d146df89330defd5219e8838f7a80e9d965a4df2
    labels:
      - "traefik.tags=akita"
      - "traefik.frontend.rule=PathPrefixStrip:/"
    volumes:
      - ${DOCKERFILES}/../akita/dev/:/akita_keys:ro
    #   - ${DOCKERFILES}/projects/selfsigned.key:/etc/nginx/ssl/nginx.key:ro
    #   - ${DOCKERFILES}/projects/selfsigned.crt:/etc/nginx/ssl/nginx.crt:ro

  nedcas-lb:
    extends: traefik-lb
    command: --web --logLevel=DEBUG --docker --docker.constraints=tag==nedcas
    ports:
      - "8880:80"

  nedcas:
    extends: nedcas-proxyable
    ports:
      - "8880:8080"

  nedcas-proxyable:
    image: plos/nedcas:develop
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=ned
      - MYSQL_USER_PASSWORD=ned
      - MYSQL_HOSTNAME=neddb
      - MYSQL_DATABASE=namedEntities
      - CAS_DB_NAME=cas
      - CAS_DB_USER=ned
      - CAS_DB_PASSWORD=ned
      - NED_SERVICE=http://nedapi:8080/v1
      - REGISTRATION_BASE_URL=http://localhost   # TODO: fix this
      - COOKIE_DOMAIN=nedcas
      - CLUSTER_MEMBERS=localhost
      - JWT_SHARED_SECRET=db714af08c2a695ac04f7dd5d146df89330defd5219e8838f7a80e9d965a4df2
      - CATALINA_OPTS=-Dlog4j.configurationFile=/usr/local/tomcat/conf/log4j2.xml # TODO: move these options into akita run.sh or Dockerfile
    labels:
      - "traefik.tags=nedcas"
      - "traefik.frontend.rule=PathPrefixStrip:/"

  nedapi-lb:
    extends: traefik-lb
    command: --web --logLevel=DEBUG --docker --docker.constraints=tag==nedapi
    ports:
      - "8888:80"

  nedapi:
    extends: nedapi-proxyable
    ports:
      - "8888:8080"

  nedapi-proxyable:
    image: plos/nedapi:develop
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=ned
      - MYSQL_USER_PASSWORD=ned
      - MYSQL_HOSTNAME=neddb
      - MYSQL_DATABASE=namedEntities
      - RINGGOLD_DATABASE=ringgold
      - SEEDS=simpledev
    labels:
      - "traefik.tags=nedapi"
      - "traefik.frontend.rule=PathPrefixStrip:/"
    volumes:
      - ${DOCKERFILES}/projects/nedapi/seeds:/seeds:ro

  neddb:
    extends: mysql
    volumes:
      - ${DOCKERFILES}/projects/nedapi/mysql-custom.cnf:/etc/mysql/conf.d/mysq-custom.cnf:ro

  traefik-lb:
    image: traefik
    ports:
      - "8000:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml

  mailcatcher:
    image: tophfr/mailcatcher
    ports:
      - "1080:80"

  plosthemes:
    image: plosthemes:master

  wombat:
    image: plos/wombat:master
    volumes:
      - ${DOCKERFILES}/../plos-themes:/root/themes
    # volumes_from:
    #   - plosthemes    # this must be specified in the inheriting file if you want it.
    ports:
      - "8015:8080"
    environment:
      - SERVER=http://rhino:8080
      - SOLR=http://solr:8080/select
      - CAS=https://localhost:8443/cas
      - EMAIL=plos-org.mail.protection.outlook.com
      - ROOT=/root/themes/
      - MEMCACHEDHOST=memcached
      # - DISABLE_COMMENTS=true
      # - ROOT_PAGE_PATH=/root/themes/content/rootPage.html

  memcached:
    image: memcached:alpine

  rhino:
    image: plos/rhino:master
    ports:
      - "8006:8080"
    volumes:
      - $HOME/datastores/ingest:/root/ingest
    environment:
      - MODE=plos
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=ambra
      - MYSQL_USER_PASSWORD=ambra
      - MYSQL_HOSTNAME=ambradb
      - MYSQL_DATABASE=ambra
      - REPO_LOCATION=http://contentrepo:8080
      - CORPUS_BUCKET=corpus
      - EDITORIAL_BUCKET=cms
      - QUEUE_LOCATION=tcp://plosqueue:61616
      - USER_API_SERVER=http://nedapi:8080
      - USER_API_USER=dev
      - USER_API_AUTH=dev
      # - SOLR_URL=http://solr:8080/solr

# RUN: ./stack.sh common run --rm indexerminion
# DEBUG: ./stack.sh common run -p 8000:8000 --rm indexerminion
  indexerminion:
    image: plos/indexerminion:accman
    volumes:
      - /tmp/indexerminion:/cache   # caches between runs
    environment:
      - RHINO_SERVICE=http://rhino:8080
      - ALM_URL=http://alm-101.soma.plos.org
      - ALM_KEY=
      - COUNTER_DATABASE_URL=jdbc:mysql://counterdb/plosreports
      - COUNTER_DATABASE=plosreports
      - COUNTER_HOSTNAME=counterdb
      - COUNTER_DATABASE_USER=ambra
      - COUNTER_DATABASE_PASSWORD=ambra
      - COUNTER_DATABASE_ROOT_PASSWORD=root
      # - SOLR_SOURCE=http://solr:8080/solr
      - SOLR_SOURCE=http://api.plos.org
      - SOLR_SOURCE_REQUEST_HANDLER=/search # required for api.plos.org
      - SOLR_TARGETS=http://solr:8080/solr
      - ARTICLE_LIST=10.1371/journal.pone.0099781
      - DEBUG_FLAGS=-Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=n # needed for running in debug mode

  counter:
    image: plos/counter:master
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=ambra
      - MYSQL_USER_PASSWORD=ambra
      - MYSQL_HOSTNAME=counterdb
      - MYSQL_DATABASE=plosreports

  plosqueue:
    image: plos/plosqueue:master
    environment:
      - SOLR_URL=http://solr:8080/solr
      - RHINO_SERVICE=http://rhino:8080
      - COUNTER_DATABASE_URL=jdbc:mysql://counterdb/plosreports
      - COUNTER_DATABASE_USER=ambra
      - COUNTER_DATABASE_PASSWORD=ambra

  ambradb:
    extends: mysql

  counterdb:
    extends: mysql

  solr:
    image: plos/solr:master
    ports:
      - "8983:8080"
    # volumes:
    #   - "$HOME/datastores/solr:/usr/local/tomcat/solr/home/data"

  contentrepo:
    image: plos/contentrepo:master
    ports:
      - "8085:8080"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=repouser
      - MYSQL_USER_PASSWORD=
      - MYSQL_HOSTNAME=repodb
      - MYSQL_DATABASE=repo
      # - STORE_TYPE=FileSystem
      # - FS_DIRECTORY=/repodata
      - STORE_TYPE=Mogile
      - MOGILE_DOMAIN=maindomain
      - MOGILE_TRACKERS=mogiletracker:7001
      # - TOMCAT_HTTP_PORT=8081   # for host networking mode
      # - TOMCAT_CONTROL_PORT=8007

  repodb:
    extends: mysql
    ports:
      - "3305:3306"

  mogiletracker:
    image: plos/mogiletracker
    environment:
      - MYSQL_HOSTNAME=mogiledb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=mogile
      - MYSQL_USER_PASSWORD=mogile
      # - MYSQL_DATABASE=mogilefs         # TODO: include this
      - MOG_NODE_HOST=mogilenode

  mogilenode:
    image: plos/mogilenode

  mogiledb:
    extends: mysql

  mysql:
    image: percona:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
