version: '2'

services:

  lagotto:
    image: lagotto:4_5_plos
    ports:
      - 80:80
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - DB_NAME=lagotto
      - DB_USERNAME=lagotto
      - DB_PASSWORD=lagotto
      - DB_HOST=mysql
      - CAS_URL=https://register.plos.org
      - MEMCACHE_SERVERS=127.0.0.1
      - REDIS_URL=redis://redis:6379

  mysql:
    image: percona:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root

  redis:
    image: redis:alpine

  couch:
    image: couchdb

  # postfix, etc.
