version: '2'

services:

  linkcuration:
    image: linkcuration:master
    ports:
      - 80:80
      - 443:443
    environment:
      - RAILS_ENV=development
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=tracker
      - MYSQL_USER_PASSWORD=tracker
      - MYSQL_HOSTNAME=curationdb
      - MYSQL_DATABASE=mediaTracker
      - CAS_URL=https://register.plos.org
    volumes:
      - ${DOCKERFILES}/projects/selfsigned.key:/etc/nginx/ssl/nginx.key:ro
      - ${DOCKERFILES}/projects/selfsigned.crt:/etc/nginx/ssl/nginx.crt:ro

  mediatracker:
    image: mediatracker:master
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=tracker
      - MYSQL_USER_PASSWORD=tracker
      - MYSQL_HOSTNAME=curationdb
      - MYSQL_DATABASE=mediaTracker

  curationdb:
    image: percona:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root


  # NOTE: not bringing up a local CAS because of limitation in the rails CAS plugin.

  # nedcas:
  #   extends:
  #     file: common.yml
  #     service: nedcas
  #
  # nedapi:
  #   extends:
  #     file: common.yml
  #     service: nedapi
  #
  # neddb:
  #   extends:
  #     file: common.yml
  #     service: neddb
