version: '2'

services:

  linkcuration:
    image: linkcuration:master
    ports:
      - 80:80
      - 443:443
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=tracker
      - MYSQL_USER_PASSWORD=tracker
      - MYSQL_HOSTNAME=curationdb
      - MYSQL_DATABASE=mediaTracker
      - CAS_URL=https://nedcas:8443
      - SSL=existingkeys  # options = none, existingkeys, generatekeys
      # TODO: remove generate keys. doesnt seem needed if existing keys works
    volumes:    # when using SSL=existingkeys
      - ${DOCKERFILES}/projects/selfsigned.key:/etc/nginx/ssl/nginx.key:ro
      - ${DOCKERFILES}/projects/selfsigned.crt:/etc/nginx/ssl/nginx.crt:ro

  curationdb:
    image: percona:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
    # volumes:    # enable to persist database between runs
    #   - /var/lib/mysql

  nedcas:
    extends:
      file: common.yml
      service: nedcas

  nedapi:
    extends:
      file: common.yml
      service: nedapi

  neddb:
    extends:
      file: common.yml
      service: neddb
