version: '2'

services:

  nedcas:
    extends:
      file: common.yml
      service: nedcas
    image: plos/nedcas:PLT-1620_CAS52-from-scratch

  nedapi:
    extends:
      file: common.yml
      service: nedapi

  neddb:
    extends:
      file: common.yml
      service: neddb
    ports:
      - "3307:3306"
