version: '2'

services:
  #
  # nedapi-lb:
  #   extends:
  #     file: common.yml
  #     service: nedapi-lb
  #
  # nedapi-consultemplate:
  #   extends:
  #     file: common.yml
  #     service: nedapi-consultemplate
  #   volumes_from:
  #     - nedapi-lb
  #
  # nedcas-ssl:
  #   extends:
  #     file: common.yml
  #     service: nedcas-ssl
  #   depends_on:
  #     - nedcas-proxyable
  #
  # nedcas-proxyable:
  #   extends:
  #     file: common.yml
  #     service: nedcas-proxyable

  nedcas:
    extends:
      file: common.yml
      service: nedcas

  nedapi-lb:
    image: dockercloud/haproxy
    links:
      - nedapi
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80

  nedapi:
    extends:
      file: common.yml
      service: nedapi-proxyable
  #
  # consulserver:
  #   extends:
  #     file: common.yml
  #     service: consulserver

  neddb:
    extends:
      file: common.yml
      service: neddb
