version: '2'

services:

  consulserver:
    image: gliderlabs/consul-server
    command: -bootstrap -ui
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"

  nginx:
    image: nginx
    ports:
      - "8081:8080"
    volumes:
      - /etc/nginx/conf.d
      - ${DOCKERFILES}/projects/named-entity.service/nginx.conf:/etc/nginx/nginx.conf:ro

  consul-template:
    image: avthart/consul-template
    command: -consul=consulserver:8500 -wait=5s -template="/tmp/nginx.ctmpl:/etc/nginx/conf.d/default.conf:docker restart configurations_nginx_1"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - ${DOCKERFILES}/projects/named-entity.service/nginx.ctmpl:/tmp/nginx.ctmpl:ro
    volumes_from:
      - nginx
    # environment:
    #   - CONSUL_TEMPLATE_LOG=debug

  nedapi:
    extends:
      file: common.yml
      service: ned-proxyable

  nedcas:
    extends:
      file: common.yml
      service: nedcas

  neddb:
    extends:
      file: common.yml
      service: neddb
