version: '2'

services:

  rhino:
    extends:
      file: common.yml
      service: rhino
    image: rhino:accman

  plosqueue:
    extends:
      file: common.yml
      service: plosqueue
    image: plosqueue:accman

  counter:
    extends:
      file: common.yml
      service: counter

  counterdb:
    image: percona:5.6
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root

  ambradb:
    extends:
      file: common.yml
      service: ambradb
    ports:
      - "3307:3306"

  solr:
    extends:
      file: common.yml
      service: solr

  contentrepo:
    extends:
      file: common.yml
      service: contentrepo

  repodb:
    extends:
      file: common.yml
      service: repodb

  mogiletracker:
    extends:
      file: common.yml
      service: mogiletracker

  mogilenode:
    extends:
      file: common.yml
      service: mogilenode
    ports:
      - "7500:7500"

  mogiledb:
    extends:
      file: common.yml
      service: mogiledb
