version: '2'

services:

  rhino:
    extends:
      file: common.yml
      service: rhino
    # image: rhino:accman

  counterdb:
    image: percona:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root

  ambradb:
    extends:
      file: common.yml
      service: ambradb
    ports:
      - "3307:3306"

  solr:
    extends:
      file: common.yml
      service: solr

  contentrepo:
    extends:
      file: common.yml
      service: contentrepo

  repodb:
    extends:
      file: common.yml
      service: repodb

  mogiletracker:
    extends:
      file: common.yml
      service: mogiletracker

  mogilenode:
    extends:
      file: common.yml
      service: mogilenode

  mogiledb:
    extends:
      file: common.yml
      service: mogiledb
