version: '2'

services:

  rhino:
    image: rhino:master
    ports:
      - 8080:8080
    volumes:
      - $HOME/datastores/ingest:/root/ingest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=ambra
      - MYSQL_USER_PASSWORD=ambra
      - MYSQL_HOSTNAME=ambradb
      - MYSQL_DATABASE=ambra
      - REPO_SERVICE=http://contentrepo:8080

  ambradb:
    image: percona:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3307:3306

  solr:
    image: solr:master
    ports:
      - 8983:8080
    volumes:
      - "$HOME/datastores/solr:/usr/local/tomcat/solr/home/data"

  contentrepo:
    image: contentrepo:master
    ports:
      - "8085:8080"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=repouser
      - MYSQL_USER_PASSWORD=
      - MYSQL_HOSTNAME=repodb
      - MYSQL_DATABASE=repo
      - MOGILE_TRACKERS=mogiletracker:7001

  repodb:
    image: percona:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3305:3306

  mogiletracker:
    image: mogiletracker
    environment:
      - MYSQL_HOSTNAME=mogiledb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=mogile
      - MYSQL_USER_PASSWORD=mogile
      - MOG_NODE_HOST=mogilenode

  mogilenode:
    image: mogilenode

  mogiledb:
    image: percona:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
