neddb:
  image: percona:5.6
  environment:
    - MYSQL_ROOT_PASSWORD=root

nedapi:
  image: nedapi:current
  links:
    - neddb:neddb
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_NED_USER=ned
    - MYSQL_NED_PASSWORD=ned
    - MYSQL_HOSTNAME=neddb
    - MYSQL_DATABASE=namedEntities

nedapitester:
  build: .
  links:
    - nedapi:nedapi   # this is what we are testing against
    - neddb:neddb     # needed because we need to wait for it to be ready
