ambradb:
  build: ambra.mysql

neddb:
  image: percona:5.6
  environment:
    - MYSQL_ROOT_PASSWORD=root

nedapi:
  image: nedapi:develop
  command: /start.sh
  links:
    - neddb:neddb
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_NED_USER=ned
    - MYSQL_NED_PASSWORD=ned
    - MYSQL_HOSTNAME=neddb
    - MYSQL_DATABASE=namedEntities

nedetl:
  image: nedetl:develop
  command: tail -f /dev/null

nedetltester:
  build: .
  links:
    - nedapi:nedapi
    - ambradb:ambradb
  volumes_from:
    - nedetl                 # TODO: fix this share
