repoapi:
  image: contentrepo:current
  command: bash +x /start.sh
  links:
    - repodb
    - node
    - tracker
  ports:
    - "8085:8080"
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_REPO_USER=repouser
    - MYSQL_REPO_PASSWORD=
    - MYSQL_HOSTNAME=repodb
    - MYSQL_DATABASE=repo


# reposvc:
#   build: reposvc
#   volumes:
#     - ../target:/build
#   links:
#     - repodb
#     - node
#     - tracker
#   ports:
#     - "8085:8080"

repodb:
  image: percona:5.6
  environment:
    - MYSQL_ROOT_PASSWORD=root
  # build: repodb.mysql
  # volumes:
  #   - ../src/main/resources:/mysql_schema

tracker:
  build: tracker
  links:
    - mogdb
    - node
  environment:
    - MOG_DB_HOST=mogdb
    - MOG_NODE_HOST=node

node:
  build: node
#  image: rail44/mogile-node

mogdb: # database for mogile
  image: orchardup/mysql
