reposvc:
  build: reposvc
  volumes:
    - ../target:/build
  links:
    - repodb
    - node
    - tracker
  ports:
    - "8085:8080"

repodb:
  build: repodb.mysql
  volumes:
    - ../src/main/resources:/mysql_schema

tracker:
  build: tracker
  links:
    - mogdb
    - node
  environment:
    - MOG_DB_HOST=mogdb
    - MOG_NODE_HOST=node

node:
  build: node
#  image: rail44/mogile-node

mogdb: # database for mogile
  image: orchardup/mysql
