default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  database: <%= ENV["MYSQL_DATABASE"] %>
  host: <%= ENV["MYSQL_HOSTNAME"] %>
  username: <%= ENV["MYSQL_USER"] %>
  password: <%= ENV["MYSQL_USER_PASSWORD"] %>

# TODO: set from environment vars

development:
  <<: *default

production:
  <<: *default
