defaults: &defaults
  solr_url: http://api.plos.org/search
  cas_host: <%= ENV["CAS_HOST"] %>
  cas_port: <%= ENV["CAS_PORT"] %>
  cas_logout_url: <%= ENV["CAS_LOGOUT_URL"] %>

# TODO: turn these values into environment vars

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
